name: FullXpression
favicon: null
layout_spectrum: 0.7978912643156946
typography_spectrum: 0.8927769723813981
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9272590873297304
  lightness: 0.816800961503759
  saturation: 0.4205423465464264
  rhythmicContrast: 0.6131163097452372
purpose: []
