name: FullXpression
favicon: null
layout_spectrum: 0.97004
typography_spectrum: 0.75101
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1a17'
    - '#da251d'
    - '#e6e6e6'
    - '#221d1a'
    - '#6b6967'
  brandStrength: 0.75
  lightness: 0.816800961503759
  saturation: 0.5
  rhythmicContrast: 0.6131163097452372
purpose: []
